# Generated by Django 5.1.4 on 2025-03-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0002_remove_admin_lab_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerequest',
            name='decision_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
