# Generated by Django 5.1.4 on 2025-01-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0002_alter_schedules_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
