# Generated by Django 5.1.4 on 2025-01-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0005_laboratory_schedules_lab_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='lab_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
