# Generated by Django 5.1.4 on 2025-03-07 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0005_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='lab_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lab_app.laboratory'),
            preserve_default=False,
        ),
    ]
