# Generated by Django 5.1.4 on 2025-01-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0006_alter_laboratory_lab_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='lab_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
