# Generated by Django 5.1.4 on 2025-01-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0007_alter_laboratory_lab_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
