# Generated by Django 5.1.4 on 2025-01-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0008_alter_schedules_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='lab_vacancy',
            field=models.IntegerField(default=5),
        ),
    ]
