# Generated by Django 5.1.4 on 2025-01-19 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0009_laboratory_lab_vacancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratory',
            old_name='lab_vacancy',
            new_name='lab_capacity',
        ),
    ]
