# Generated by Django 5.1.4 on 2025-01-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0010_rename_lab_vacancy_laboratory_lab_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='fallback_icon_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='icon_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='lab_vacancy',
            field=models.IntegerField(default=5),
        ),
    ]
