# Generated by Django 5.1.4 on 2025-02-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0011_laboratory_fallback_icon_url_laboratory_icon_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='lab_vacancy',
        ),
    ]
