# Generated by Django 5.1.4 on 2025-02-13 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0012_remove_laboratory_lab_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hours', models.FloatField()),
                ('num_bookings', models.IntegerField()),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_app.laboratory')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'lab_id'), name='daily_unique')],
            },
        ),
    ]
