# Generated by Django 5.1.4 on 2025-02-15 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0013_daily'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.TextField(max_length=25)),
                ('total_hours', models.FloatField()),
                ('num_bookings', models.IntegerField()),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_app.laboratory')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('month', 'lab_id'), name='monthly_unique')],
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('week_int', models.TextField(max_length=25)),
                ('total_hours', models.FloatField()),
                ('num_bookings', models.IntegerField()),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_app.laboratory')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('week_int', 'lab_id'), name='weekly_unique')],
            },
        ),
    ]
