# Generated by Django 5.1.4 on 2025-02-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0014_month_week'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='week',
            name='weekly_unique',
        ),
        migrations.RenameField(
            model_name='week',
            old_name='week_int',
            new_name='week_label',
        ),
        migrations.AddField(
            model_name='week',
            name='week_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.UniqueConstraint(fields=('week_num', 'lab_id'), name='weekly_unique'),
        ),
    ]
