# Generated by Django 5.1.4 on 2025-02-25 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0015_remove_week_weekly_unique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_date', models.DateField()),
                ('schedule_from', models.TimeField()),
                ('schedule_to', models.TimeField()),
                ('status', models.CharField(max_length=30)),
                ('decision_date', models.DateField()),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_app.admin')),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_app.laboratory')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_app.user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('username', 'lab_id', 'schedule_date', 'schedule_from', 'schedule_to', 'status'), name='unique_schedule_request')],
            },
        ),
    ]
