# Generated by Django 5.1.4 on 2025-02-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0016_admin_schedulerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerequest',
            name='status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
