# Generated by Django 5.1.4 on 2025-02-26 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0017_alter_schedulerequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulerequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='schedulerequest',
            name='lab_id',
        ),
        migrations.RemoveField(
            model_name='schedulerequest',
            name='username',
        ),
        migrations.AlterField(
            model_name='schedules',
            name='lab_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lab_app.laboratory'),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='ScheduleRequest',
        ),
    ]
